### ISSUE TITLE
Trashed content crashed admin tag view

### ISSUE THREAD

**Issue by iherak** [netgen/TagsBundle#154]
If content that is related to the tag is moved to trash, it is not possible to view the tag in admin - related content is returned without main location so it fails with `Cannot generate an UrlAlias route for content without main location.`

**Comment by emodric** [comment]
@iherak Fixed in 3.4.12

Please test and report back :)

**Comment by iherak** [comment]
Tested and confirmed it works now! Thank you @emodric!

**Comment by iherak** [comment]
Hm, seems this does not fix it completely, it still crashes on `related_content` (showing all related content of the tag).

**Comment by emodric** [comment]
This might not be easily fixed, I'm afraid. Fetching related content is done by using `TagsService::getRelatedContent`, which internally uses eZ search service which, it seems, does not support filtering out content without main location.

The issue lies in paging, that is, fetching the count of content items. While it is possible to filter out content without the main locations after the fetch, by doing that, the count and paging will go out of sync.

I have no good solution for this currently, so I'm accepting ideas :)

**Comment by iherak** [comment]
Maybe we could take care of this at template level - do not generate a link if the content does not have main location id set? We just show content information without the link?

**Comment by emodric** [comment]
Sounds good 👍

**Comment by emodric** [comment]
Fixed in 3.4.13
